service: josephcaba

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

  iam:
    role: arn:aws:iam::944585571319:role/LabRole

functions:
  saveTaskToken:
    handler: src/workers/saveTaskToken.handler

  createOrder:
    handler: src/orders/createOrder.handler
    events:
      - httpApi:
          path: /orders
          method: post

  getOrder:
    handler: src/orders/getOrder.handler
    events:
      - httpApi:
          path: /orders/{orderId}
          method: get

  getOrderStatus:
    handler: src/orders/getOrderStatus.handler
    events:
      - httpApi:
          path: /orders/{orderId}/status
          method: get

  updateOrderStatus:
    handler: src/orders/updateOrderStatus.handler
    events:
      - httpApi:
          path: /orders/{orderId}/status
          method: put

  startCooking:
    handler: src/workers/startCooking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-cooking
          method: post

  finishCooking:
    handler: src/workers/finishCooking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-cooking
          method: post

  startPacking:
    handler: src/workers/startPacking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-packing
          method: post

  finishPacking:
    handler: src/workers/finishPacking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-packing
          method: post

  startDelivery:
    handler: src/workers/startDelivery.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-delivery
          method: post

  finishDelivery:
    handler: src/workers/finishDelivery.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-delivery
          method: post

resources:
  Resources:

    PapaJohnsEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: PapaJohnsEventBus

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S

        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE

    OrderHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrderHistory
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: order_id
            AttributeType: S
          - AttributeName: event_time
            AttributeType: S

        KeySchema:
          - AttributeName: order_id
            KeyType: HASH
          - AttributeName: event_time
            KeyType: RANGE

    WorkersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Workers
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: worker_id
            AttributeType: S

        KeySchema:
          - AttributeName: worker_id
            KeyType: HASH

    TaskTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTokens
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: order_id
            AttributeType: S

        KeySchema:
          - AttributeName: order_id
            KeyType: HASH
