service: josephcaba

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

  iam:
    role: arn:aws:iam::944585571319:role/LabRole

functions:
  saveTaskToken:
    handler: src/workers/saveTaskToken.handler

  verifyMainItemReady:
    handler: src/extras/verifyMainItemReady.handler

  prepareDrink:
    handler: src/extras/prepareDrink.handler

  prepareAppetizer:
    handler: src/extras/prepareAppetizer.handler

  getDashboardSummary:
    handler: src/dashboard/getSummary.handler
    events:
      - httpApi:
          path: /dashboard/summary
          method: get

  notifyRappi:
    handler: src/notifications/notifyRappi.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - RappiNotificationsQueue
              - Arn
          batchSize: 1

  createOrder:
    handler: src/orders/createOrder.handler
    events:
      - httpApi:
          path: /orders
          method: post

  getOrder:
    handler: src/orders/getOrder.handler
    events:
      - httpApi:
          path: /orders/{orderId}
          method: get

  getOrderStatus:
    handler: src/orders/getOrderStatus.handler
    events:
      - httpApi:
          path: /orders/{orderId}/status
          method: get

  updateOrderStatus:
    handler: src/orders/updateOrderStatus.handler
    events:
      - httpApi:
          path: /orders/{orderId}/status
          method: put

  startCooking:
    handler: src/workers/startCooking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-cooking
          method: post

  finishCooking:
    handler: src/workers/finishCooking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-cooking
          method: post

  startPacking:
    handler: src/workers/startPacking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-packing
          method: post

  finishPacking:
    handler: src/workers/finishPacking.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-packing
          method: post

  readyForCustomer:
    handler: src/workers/readyForCustomer.handler

  startDelivery:
    handler: src/workers/startDelivery.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/start-delivery
          method: post

  finishDelivery:
    handler: src/workers/finishDelivery.handler
    events:
      - httpApi:
          path: /workers/orders/{orderId}/finish-delivery
          method: post

resources:
  Resources:

    PapaJohnsEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: PapaJohnsEventBus

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S

        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE

    OrderHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrderHistory
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: order_id
            AttributeType: S
          - AttributeName: event_time
            AttributeType: S

        KeySchema:
          - AttributeName: order_id
            KeyType: HASH
          - AttributeName: event_time
            KeyType: RANGE

    WorkersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Workers
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: worker_id
            AttributeType: S

        KeySchema:
          - AttributeName: worker_id
            KeyType: HASH

    TaskTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTokens
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: order_id
            AttributeType: S

        KeySchema:
          - AttributeName: order_id
            KeyType: HASH

    RappiNotificationsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: RappiNotificationsDLQ

    RappiNotificationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: RappiNotificationsQueue
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - RappiNotificationsDLQ
              - Arn
          maxReceiveCount: 3

    RappiNotificationsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: RappiNotificationsQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sqs:SendMessage
              Resource:
                Fn::GetAtt:
                  - RappiNotificationsQueue
                  - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: arn:aws:events:us-east-1:944585571319:rule/PapaJohnsEventBus/NotifyRappiRule
